name: Node CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - "feature/*"
      - "maintain/*"
      - "shinyoshiaki/*"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: prepare
        run: |
          sudo apt-get update
          sudo apt-get -y install libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config libsrtp2-dev libasound2-dev libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio
          npm i
          cd e2e
          npm i
          npx playwright install chromium
          cd ../
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3    
      - name: test
        env:
          CI: true
        run: |
          npm run test
